name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
      env:
        RUSTFLAGS: -D warnings
    - name: Run tests
      run: cargo test --verbose
      env:
        RUSTFLAGS: -D warnings
    - name: Check formatting
      run: cargo fmt -- --check
